export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FAILED_FETCH_DATA = 'FAILED_FETCH_DATA';
export const PURCHASE_BURGER_SUCESS = 'PURCHASE_BURGER_SUCESS';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_INIT = 'PURCHASE_BURGER_INIT';
